global e1;
global bg;
global p;
global w;
global Pause_button;
global Omega;
global len1;
global len2;
global len3;
global len4;
global Radius;
global leng;
global sp1;
global sp2;
global sp3;
global sp4;
p = 1;
e1 = 0;
w = 1;
%Creating Buttons in the button group
%set(Radius,'Visible','off');
clear Radius;
clear leng;
%set(leng,'Visible','off');
              
len1 = uicontrol(bg,'Style',...
                  'edit',...
                  'units','normalized',...
                  'BackgroundColor',[0 1 0],...
                  'String','Enter the Crank Radius',...
                  'ToolTip','Enter only number here',...
                  'Position',[0.1 0.825 0.8 0.05],...
                  'FontSize',10);
              
len2 = uicontrol(bg,'Style','edit',...
                  'String','Enter Connecting Rod Length',...
                  'BackgroundColor',[0 1 0],...
                  'units','normalized',...
                  'ToolTip','Enter only number here',...
                  'Position',[0.1 0.725 0.8 0.05],...
                  'FontSize',10);
     
len3 = uicontrol(bg,'Style','edit',...
                  'String','Enter Connecting Rod Length',...
                  'BackgroundColor',[0 1 0],...
                  'units','normalized',...
                  'ToolTip','Enter only number here',...
                  'Position',[0.1 0.625 0.8 0.05],...
                  'FontSize',10);
              
len4 = uicontrol(bg,'Style','edit',...
                  'String','Enter Connecting Rod Length',...
                  'BackgroundColor',[0 1 0],...
                  'units','normalized',...
                  'ToolTip','Enter only number here',...
                  'Position',[0.1 0.525 0.8 0.05],...
                  'FontSize',10);
    
              
Omega = uicontrol(bg,'Style','slider',...
                  'String','Angular Velocity',...
                  'BackgroundColor',[0 1 0],...
                  'units','normalized',...
                  'Max',10,'Min',1,'value',1,...
                  'ToolTip','Change speed of rotation using the slider',...
                  'Position',[0.1 0.42 0.8 0.05],...
                  'callback',{@Angular});
             

start_button = uicontrol(bg,'Style',...
                      'pushbutton',...
                      'String','Start',...
                      'units','normalized',...
                      'Position',[0.1 0.3 0.8 0.075],...
                      'BackgroundColor',[1 0 0],...
                      'FontSize',12,...
                      'FontWeight','Bold',...
                      'ToolTip','Press to start or stop the simulation',...
                      'callback',{@Slider_crank,len1,len2,len3,len4});
                  
Pause_button = uicontrol(bg,'Style',...
                      'pushbutton',...
                      'String','Pause',...
                      'units','normalized',...
                      'Position',[0.1 0.2 0.8 0.075],...
                      'BackgroundColor',[1 0 0],...
                      'FontSize',12,...
                      'FontWeight','Bold',...
                      'ToolTip','Press to Pause the simulation',...
                      'callback',{@Pause});                  
              
Exit_window = uicontrol(bg,'Style','pushbutton',...
                  'String','Exit',...
                  'units','normalized',...
                  'Position',[0.1 0.1 0.8 0.075],...
                  'BackgroundColor',[1 0 0],...
                  'FontSize',12,...
                  'FontWeight','Bold',...
                  'ToolTip','Press to exit the window',...
                  'callback',{@Exit});
         