clc;
clear;
global e1;
global gcf;
global bg;
global p;
global w;
global Dropdown;
p = 1;
e1 = 0;
w = 1;
gcf = figure('Name','Slider-Crank Mechanism','NumberTitle','off');
set(gcf,'Color',[0.8 0.8 0]);
set(gcf,'units','normalized',...
    'Position',[0 0 1 1]);
bg = uibuttongroup('Visible','off',...
                  'Position',[0 0 .15 1],...
                  'BackgroundColor', [0 0 1]);
              
%Creating Button in the button group
Dropdown = uicontrol(bg,'Style','popup',...
                  'String', {'Choose the mechanism','Fourbar','SliderCrank'},...
                  'units','normalized',...
                  'ToolTip','Choose which mechanism simulation is required',...
                  'Position',[0.1 0.875 0.8 0.1],...
                  'FontSize',14,...
                  'ForegroundColor',[0 1 0],...
                  'BackgroundColor', [0 0 1],...
                  'callback',{@MechType});
              
set(bg,'Visible','on');