global e1;
global bg;
global p;
global w;
global Omega start_button Pause_button Exit_window;
global Radius leng;
p = 1;
e1 = 0;
w = 1;
set(gcf,'Name','Slidercrank Mechanism');

Radius = uicontrol(bg,'Style',...
                  'edit',...
                  'units','normalized',...
                  'BackgroundColor',[0 1 0],...
                  'String','Enter the Crank Radius',...
                  'ToolTip','Enter only number here',...
                  'Position',[0.1 0.8 0.8 0.075],...
                  'FontSize',10);
              
leng = uicontrol(bg,'Style','edit',...
                  'String','Enter Connecting Rod Length',...
                  'BackgroundColor',[0 1 0],...
                  'units','normalized',...
                  'ToolTip','Enter only number here',...
                  'Position',[0.1 0.675 0.8 0.075],...
                  'FontSize',10);
              
Omega = uicontrol(bg,'Style','slider',...
                  'String','Angular Velocity',...
                  'BackgroundColor',[0 1 0],...
                  'units','normalized',...
                  'Max',10,'Min',1,'value',1,...
                  'ToolTip','Change speed of rotation using the slider',...
                  'Position',[0.1 0.575 0.8 0.05],...
                  'callback',{@Angular});
             

start_button = uicontrol(bg,'Style',...
                      'pushbutton',...
                      'String','Start',...
                      'units','normalized',...
                      'Position',[0.1 0.4 0.8 0.075],...
                      'BackgroundColor',[1 0 0],...
                      'FontSize',12,...
                      'FontWeight','Bold',...
                      'ToolTip','Press to start or stop the simulation',...
                      'callback',{@Slider_crank,Radius,leng});
                  
Pause_button = uicontrol(bg,'Style',...
                      'pushbutton',...
                      'String','Pause',...
                      'units','normalized',...
                      'Position',[0.1 0.25 0.8 0.075],...
                      'BackgroundColor',[1 0 0],...
                      'FontSize',12,...
                      'FontWeight','Bold',...
                      'ToolTip','Press to Pause the simulation',...
                      'callback',{@Pause});                  
              
Exit_window = uicontrol(bg,'Style','pushbutton',...
                  'String','Exit',...
                  'units','normalized',...
                  'Position',[0.1 0.1 0.8 0.075],...
                  'BackgroundColor',[1 0 0],...
                  'FontSize',12,...
                  'FontWeight','Bold',...
                  'ToolTip','Press to exit the window',...
                  'callback',{@Exit});