clc;
clear all;
global e1;
global gcf;
global bg;
global p;
global Pause_button;
p = 1;
e1 = 0;
gcf = figure('Name','Slider-Crank Mechanism','NumberTitle','off');
set(gcf,'Color',[0.8 0.8 0]);
set(gcf,'units','normalized',...
    'Position',[0 0 1 1]);
bg = uibuttongroup('Visible','off',...
                  'Position',[0 0 .15 1],...
                  'BackgroundColor', [0 0 1]);
              
%Creating Buttons in the button group
Radius = uicontrol(bg,'Style',...
                  'edit',...
                  'units','normalized',...
                  'BackgroundColor',[0 1 0],...
                  'String','Enter the Crank Radius',...
                  'ToolTip','Enter only number here',...
                  'Position',[0.1 0.8 0.8 0.1]);
              
leng = uicontrol(bg,'Style','edit',...
                  'String','Enter Connecting Rod Length',...
                  'BackgroundColor',[0 1 0],...
                  'units','normalized',...
                  'ToolTip','Enter only number here',...
                  'Position',[0.1 0.65 0.8 0.1]);

start_button = uicontrol(bg,'Style',...
                      'pushbutton',...
                      'String','Start',...
                      'units','normalized',...
                      'Position',[0.1 0.45 0.8 0.1],...
                      'BackgroundColor',[1 0 0],...
                      'FontSize',12,...
                      'FontWeight','Bold',...
                      'ToolTip','Press to start or stop the simulation',...
                      'callback',{@Slider_crank,Radius,leng});
                  
Pause_button = uicontrol(bg,'Style',...
                      'pushbutton',...
                      'String','Pause',...
                      'units','normalized',...
                      'Position',[0.1 0.3 0.8 0.1],...
                      'BackgroundColor',[1 0 0],...
                      'FontSize',12,...
                      'FontWeight','Bold',...
                      'ToolTip','Press to Pause the simulation',...
                      'callback',{@Pause});                  
              
Exit_window = uicontrol(bg,'Style','pushbutton',...
                  'String','Exit',...
                  'units','normalized',...
                  'Position',[0.1 0.15 0.8 0.1],...
                  'BackgroundColor',[1 0 0],...
                  'FontSize',12,...
                  'FontWeight','Bold',...
                  'ToolTip','Press to exit the window',...
                  'callback',{@Exit});
              
set(bg,'Visible','on');