
clc;
clear all;
global e1;
global gcf;
global bg;
global p;
global w;
global Pause_button;
global Omega;
global Radius;
global leng;
p = 1;
e1 = 0;
w = 1;
gcf = figure('Name','Slider-Crank Mechanism','NumberTitle','off');
set(gcf,'Color',[0.8 0.8 0]);
set(gcf,'units','normalized',...
    'Position',[0 0 1 1]);
bg = uibuttongroup('Visible','off',...
                  'Position',[0 0 .15 1],...
                  'BackgroundColor', [0 0 1]);
              
%Creating Buttons in the button group
Default_1 = uicontrol(bg,'Style','checkbox',...
                  'String','Default 1',...
                  'units','normalized',...
                  'ToolTip','Check this box for first default conditions',...
                  'Position',[0.3 0.95 0.8 0.05],...
                  'FontSize',14,...
                  'ForegroundColor',[0 1 0],...
                  'BackgroundColor', [0 0 1],...
                  'callback',{@Default1}); 
        
Default_2 = uicontrol(bg,'Style','checkbox',...
                  'String','Default 2',...
                  'units','normalized',...
                  'ToolTip','Check this box for second default conditions',...
                  'Position',[0.3 0.9 0.8 0.05],...
                  'FontSize',14,...
                  'ForegroundColor',[0 1 0],...
                  'BackgroundColor', [0 0 1],...
                  'callback',{@Default2});
             
Default_3 = uicontrol(bg,'Style','checkbox',...
                  'String','Default 3',...
                  'units','normalized',...
                  'ToolTip','Check this box for thrid default conditions',...
                  'Position',[0.3 0.85 0.8 0.05],...
                  'BackgroundColor', [0 0 1],...
                  'ForegroundColor',[0 1 0],...
                  'FontSize',14,...
                  'callback',{@Default3});
              
Radius = uicontrol(bg,'Style',...
                  'edit',...
                  'units','normalized',...
                  'BackgroundColor',[0 1 0],...
                  'String','Enter the Crank Radius',...
                  'ToolTip','Enter only number here',...
                  'Position',[0.1 0.725 0.8 0.1]);
              
leng = uicontrol(bg,'Style','edit',...
                  'String','Enter Connecting Rod Length',...
                  'BackgroundColor',[0 1 0],...
                  'units','normalized',...
                  'ToolTip','Enter only number here',...
                  'Position',[0.1 0.575 0.8 0.1]);
              
Omega = uicontrol(bg,'Style','slider',...
                  'String','Angular Velocity',...
                  'BackgroundColor',[0 1 0],...
                  'units','normalized',...
                  'Max',10,'Min',1,'value',1,...
                  'ToolTip','Change speed of rotation using the slider',...
                  'Position',[0.1 0.475 0.8 0.05],...
                  'callback',{@Angular});
             

start_button = uicontrol(bg,'Style',...
                      'pushbutton',...
                      'String','Start',...
                      'units','normalized',...
                      'Position',[0.1 0.325 0.8 0.1],...
                      'BackgroundColor',[1 0 0],...
                      'FontSize',12,...
                      'FontWeight','Bold',...
                      'ToolTip','Press to start or stop the simulation',...
                      'callback',{@Slider_crank,Radius,leng});
                  
Pause_button = uicontrol(bg,'Style',...
                      'pushbutton',...
                      'String','Pause',...
                      'units','normalized',...
                      'Position',[0.1 0.175 0.8 0.1],...
                      'BackgroundColor',[1 0 0],...
                      'FontSize',12,...
                      'FontWeight','Bold',...
                      'ToolTip','Press to Pause the simulation',...
                      'callback',{@Pause});                  
              
Exit_window = uicontrol(bg,'Style','pushbutton',...
                  'String','Exit',...
                  'units','normalized',...
                  'Position',[0.1 0.025 0.8 0.1],...
                  'BackgroundColor',[1 0 0],...
                  'FontSize',12,...
                  'FontWeight','Bold',...
                  'ToolTip','Press to exit the window',...
                  'callback',{@Exit});
              
set(bg,'Visible','on');