global gcf bg;
global p w e1;
global Omega start_button Pause_button Exit_window;
global Radius leng1 leng2;
p = 1;
e1 = 0;
w = 1;
set(gcf,'Name','Whitworth Mechanism');
bg = uibuttongroup('Visible','off',...
                  'Position',[0 0 .15 1],...
                  'BackgroundColor', [0 0 1]);
              
%Creating Buttons in the button group
              
Radius = uicontrol(bg,'Style','edit',...
                  'units','normalized',...
                  'BackgroundColor',[0 1 0],...
                  'String','Enter the Crank Radius',...
                  'ToolTip','Enter only number here',...
                  'FontSize',10,...
                  'Position',[0.1 0.825 0.8 0.05]);
              
leng1 = uicontrol(bg,'Style','edit',...
                  'String','Enter length of slotted lever',...
                  'BackgroundColor',[0 1 0],...
                  'units','normalized',...
                  'ToolTip','Enter only number here',...
                  'FontSize',10,...
                  'Position',[0.1 0.725 0.8 0.05]);
              
leng2 = uicontrol(bg,'Style','edit',...
                  'String','Enter Connecting Rod Length',...
                  'BackgroundColor',[0 1 0],...
                  'units','normalized',...
                  'ToolTip','Enter only number here',...
                  'FontSize',10,...
                  'Position',[0.1 0.625 0.8 0.05]);
              
Omega = uicontrol(bg,'Style','slider',...
                  'String','Angular Velocity',...
                  'BackgroundColor',[0 1 0],...
                  'units','normalized',...
                  'Max',10,'Min',1,'value',1,...
                  'ToolTip','Change speed of rotation using the slider',...
                  'Position',[0.1 0.525 0.8 0.05],...
                  'callback',{@Angular});
             

start_button = uicontrol(bg,'Style',...
                      'pushbutton',...
                      'String','Start',...
                      'units','normalized',...
                      'Position',[0.1 0.375 0.8 0.1],...
                      'BackgroundColor',[1 0 0],...
                      'FontSize',12,...
                      'FontWeight','Bold',...
                      'ToolTip','Press to start or stop the simulation',...
                      'callback',{@WW,Radius,leng1,leng2});
                  
Pause_button = uicontrol(bg,'Style',...
                      'pushbutton',...
                      'String','Pause',...
                      'units','normalized',...
                      'Position',[0.1 0.225 0.8 0.1],...
                      'BackgroundColor',[1 0 0],...
                      'FontSize',12,...
                      'FontWeight','Bold',...
                      'ToolTip','Press to Pause the simulation',...
                      'callback',{@Pause});                  
              
Exit_window = uicontrol(bg,'Style','pushbutton',...
                  'String','Exit',...
                  'units','normalized',...
                  'Position',[0.1 0.075 0.8 0.1],...
                  'BackgroundColor',[1 0 0],...
                  'FontSize',12,...
                  'FontWeight','Bold',...
                  'ToolTip','Press to exit the window',...
                  'callback',{@Exit});
              
set(bg,'Visible','on');